Отображение иконки корзины
js-tasks-ru/jsbasic-20201113_udin-petr pull request #11
Opened 2020-12-21 20:13 UTC by PetrUdin

2020-12-21 20:52 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Учебный проект: Список товаров
- после создания должны быть показаны карточки для всех товаров
- должен объединять объекты filters между разными вызовами
- товары должны быть отфильтрованы по полю category
- товары должны быть отфильтрованы по полю maxSpiciness
- товары должны быть отфильтрованы по полю noNuts
- товары должны быть отфильтрованы по полю vegeterianOnly
```
```diff
Учебный проект: Иконка корзины
+ иконка корзины должна быть скрыта
+ иконка должна смещаться на 20px правее от первого элемент в документе с классом `container`
+ иконка должна быть спозиционирована фиксированно
+ иконка должна смещаться на 10px левее главного контейнера
+ иконка должна быть спозиционирована фиксированно
+ иконка корзины должна быть видимой на странице
```

2020-12-22 05:31 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Учебный проект: Иконка корзины
+ иконка корзины должна быть видимой на странице
+ иконка должна быть спозиционирована фиксированно
+ иконка должна смещаться на 10px левее главного контейнера
+ иконка должна быть спозиционирована фиксированно
+ иконка должна смещаться на 20px правее от первого элемент в документе с классом `container`
+ иконка корзины должна быть скрыта
```
```diff
Учебный проект: Список товаров
+ после создания должны быть показаны карточки для всех товаров
+ товары должны быть отфильтрованы по полю vegeterianOnly
+ товары должны быть отфильтрованы по полю maxSpiciness
+ товары должны быть отфильтрованы по полю category
+ товары должны быть отфильтрованы по полю noNuts
+ должен объединять объекты filters между разными вызовами
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-12-22 07:08 UTC, koalex requested changes
Исправь замечание

2020-12-22 07:08 UTC, koalex commented on 8-module/2-task/index.js
> +  }В
что за **`B`** ? Удали

2020-12-22 07:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-12-22 08:44 UTC, koalex approved these changes

2020-12-22 08:44 UTC, merged